version: '3.0'
 
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '8080:80'
    depends_on:
      - app
      - db
    
    volumes:
      - ./app:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d


     
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment: 
      POSTGRES_DB: blog
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: password 

  app:
    container_name: testTech
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
        - "9000:9000"
    working_dir: /var/www
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgAdmin
    ports:
      - "5050:80"
    depends_on:
      - db 
    environment:
      PGADMIN_DEFAULT_EMAIL: mehdihassouf@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: root 


  